# Default values for on-demand-micro-services-deployment-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # uncomment and fill registry name
  # registry:
  registry: 192.168.3.94:8888
  name: library/helm-web-api
  tag: v20190822
  pullPolicy: Always

service:
  type: NodePort
  port: 37777

namespace: kube-system

# for the ingress functionallity - the ingress is the controller which exposes the newly deployed service
# Refer to the docs for more details
ingress:
  ingressNamespace: default
  minPort: 20000
  maxPort: 30000
  ingressLabel: ingress

# configuration for the rbac namespaces, service accounts, roles and binding names
rbac:
  helmServiceAccount: helm
  helmRole: cluster-admin
  tillerServiceAccount: tiller
  tillerRoleBindingName: tiller-user-binding
  tillerNamespace: kube-system

volumn：
  configMapName: kube-config-4-helm
